apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 24.4.11
    helm:
      valuesObject:
        auth:
          adminUser: admin
          adminPassword: "admin"
        postgresql:
          enabled: false
        production: false
        proxy: edge
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1Gi
        service:
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: keycloak.local
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
