configs:
  params:
    server.insecure: true

server:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

applicationSet:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

notifications:
  enabled: false

redis:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

dex:
  enabled: false
