apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.29.1
    helm:
      valuesObject:
        global:
          dev: true
        server:
          dev:
            enabled: true
            devRootToken: "root"
          standalone:
            enabled: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
          # Ingress to access Vault UI
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: vault.local
                paths:
                  - /
        ha:
          enabled: false
        ui:
          enabled: true
          serviceType: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
